version: '3'

services: 
    mongodb:
        image: mongo
        container_name: Project21-mongo
        restart: unless-stopped
        command: mongod
        ports:
            - "27017:27017"
            - "28017:28017"
        volumes: 
            - mongodbdata:/data/db
        networks: 
            - backend
    
    backend-server:
        container_name: Project21-backend
        build: 
            context: ./
            dockerfile: Dockerfile
        environment: 
            MONGO_CONTAINER_NAME: 'Project21-mongo'
            FRONTEND_CONTAINER_NAME: 'Project21-frontend'
            BACKEND_CONTAINER_NAME: 'Project21-backend'
        ports: 
            - "8000:8000"
        volumes: 
            - ./Database:/Backend/Database
        networks: 
            - frontend
            - backend
        depends_on: 
            - mongodb

    frontend-server:
        container_name: Project21-frontend
        build: 
            context: Frontend/
            dockerfile: Dockerfile
        environment: 
            REACT_APP_FRONTEND_CONTAINER_NAME: 'Project21-frontend'
            REACT_APP_BACKEND_CONTAINER_NAME: 'Project21-backend'
        tty: true
        ports: 
            - "3000:3000"
        networks: 
            - frontend
        depends_on: 
            - backend-server

networks: 
    frontend:
        driver: bridge
    backend:
        driver: bridge

volumes: 
    mongodbdata:
        driver: local